package com.ywb.springbootwebdao.io.dao;


import com.ywb.springbootwebdao.io.model.UserInfor;
import com.ywb.springbootwebdao.io.model.UserInforKey;

public interface UserInforMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(UserInforKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated
     */
    int insert(UserInfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated
     */
    int insertSelective(UserInfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated
     */
    UserInfor selectByPrimaryKey(UserInforKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserInfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfor record);
}