#mysql 数据源
spring:
  datasource:
    url: jdbc:mysql://localhots:3306/springboot
    username: root
    password: root
    driver-class-name: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapping/*.xml    #对应mapper映射xml文件的所在路
  type-aliases-package: com.ywb.springbootwebdao.io.model   #对应实体类的路径

  #服务启动端口号
server:
  port: 8082